/**
 * Dictionary — dashboard view namespaces (overview, bills, transfer, analytics, budgets).
 * OWNED BY: dashboard-views conversion task. Add keys here, do not create other dict files.
 * Naming: overview.*, bills.*, transfer.*, analytics.*, budget.* — ar values MUST be copied
 * verbatim from the existing UI. Cross-view shared strings (errors, cancel, loading, IQD
 * suffix) live under common.* in this file.
 */
export const ar: Record<string, string> = {
  /* ---- shared across dashboard views ---- */
  "common.iqd": "د.ع",
  "common.unexpectedError": "خطأ غير متوقع",
  "common.opFailed": "فشلت العملية",
  "common.tryAgain": "حاول مرة أخرى",
  "common.cancel": "إلغاء",
  "common.loading": "جاري التحميل…",

  /* ---- overview ---- */
  "overview.greetingMorning": "صباح الخير",
  "overview.greetingAfternoon": "نهارك سعيد",
  "overview.greetingEvening": "مساء الخير",
  "overview.greetingLine": "{greeting} يا {name} {emoji} — رصيدك المتاح",
  "overview.walletBadge": "محفظة أور پاي",
  "overview.demoBadge": "حساب تجريبي",
  "overview.payBillBtn": "ادفع فاتورة",
  "overview.transferBtn": "حوّل",
  "overview.topUpBtn": "عبّي المحفظة",
  "overview.askUrBtn": "اسأل أور",
  "overview.overdueAlertStart": "عندك",
  "overview.overdueAlertEnd": "فاتورة متأخرة — خلّي أور يخلصها قبل لا تتراكم.",
  "overview.showBillsBtn": "اعرضها",
  "overview.upcomingBillsTitle": "فواتير بتستنى",
  "overview.billsCountSuffix": "فواتير بمجموع",
  "overview.viewAllBtn": "الكل",
  "overview.recentTitle": "آخر الحركات",
  "overview.fullHistoryBtn": "السجل الكامل",
  "overview.noUnpaidDesc": "عاش! جرّب توليد فاتورة تجريبية من صفحة الفواتير أو اسأل أور.",
  "overview.noTxns": "ما عندك معاملات بعد — ابدأ بدفع فاتورة!",
  "overview.tryUrTitle": "جرّب أور الآن",
  "overview.tryUrDesc": "اكتبله: «ادفع فاتورة الكهرباء» أو «شكد رصيدي» — وبيتم كل شي بمحادثة.",
  "overview.chipBalance": "شكد رصيدي؟",
  "overview.chipBills": "فواتيري",
  "overview.chipPayBill": "ادفع فاتورة الكهرباء",
  "overview.openChatBtn": "افتح المحادثة",
  "overview.doneCloseBtn": "تم، إغلاق",
  "overview.topupToastTitle": "تمت التعبئة ✅",
  "overview.topupToastDesc": "أضفنا {amount} — رصيدك الآن {balance}",
  "overview.topupDialogTitle": "عبّي محفظتك",
  "overview.topupDialogDesc": "إيداع نقدي محاكى عند وكيل أور پاي — يتطلب تأكيد الـ PIN.",
  "overview.topupContinueBtn": "متابعة التعبئة",
  "overview.topupPinTitle": "تأكيد تعبئة المحفظة",
  "overview.topupPinDesc": "إيداع نقدي — وكيل أور پاي (محاكاة)",
  "overview.topupPinConfirm": "نفّذ التعبئة",

  /* ---- bills ---- */
  "bills.title": "الفواتير",
  "bills.unpaidTotal": "مجموع غير المدفوع: {total}",
  "bills.allPaid": "كل فواتيرك مدفوعة 🎉",
  "bills.count": "{n} فاتورة",
  "bills.simulateBtn": "ولّد فاتورة تجريبية",
  "bills.tabUnpaid": "غير مدفوعة",
  "bills.tabPaid": "مدفوعة",
  "bills.tabAll": "الكل",
  "bills.noUnpaidTitle": "ما عندك فواتير غير مدفوعة",
  "bills.noneInFilterTitle": "ما هني فواتير بهذا التصنيف",
  "bills.emptyDesc": "ولّد فاتورة تجريبية وجرّب عملية الدفع كاملة مع PIN وإيصال مرجعي.",
  "bills.simulateShortBtn": "ولّد فاتورة",
  "bills.payConfirmTitle": "تأكيد دفع الفاتورة",
  "bills.noPeriod": "بدون فترة",
  "bills.payNowBtn": "ادفع الآن",
  "bills.paidToastTitle": "تم الدفع بنجاح ✅",
  "bills.receiptTitle": "إيصال الدفع",
  "bills.receiptDesc": "تفاصيل العملية الناجحة",
  "bills.simulateDesc": "فاتورة جديدة تضاف لقائمتك — مثالية لتجربة المساعد أور أو الدفع المباشر.",
  "bills.categoryLabel": "الصنف",
  "bills.billerLabel": "الجهة",
  "bills.selectBiller": "اختر الجهة",
  "bills.subscriberLabel": "رقم الاشتراك",
  "bills.amountLabel": "المبلغ (د.ع)",
  "bills.generateBtn": "ولّد الفاتورة",
  "bills.generatedToastTitle": "تم توليد الفاتورة ✨",
  "bills.generatedToastDesc": "صارت جاهزة بالقائمة — ادفعها أو خلّي أور يدفعها",
  "bills.generateFailTitle": "فشل التوليد",

  /* ---- transfer ---- */
  "transfer.ttlExpiring": "على وشك الانتهاء",
  "transfer.ttlHm": "{h} سا و{m} د",
  "transfer.ttlMins": "{m} دقيقة",
  "transfer.ttlExpiresIn": "تنتهي بعد {label}",
  "transfer.pendingTitle": "طلبات معلّقة",
  "transfer.pendingHint": "تنتهي تلقائيًا بعد 24 ساعة من إنشائها",
  "transfer.badgeOutgoing": "صادرة — بانتظار تأكيدك",
  "transfer.badgeIncoming": "واردة — بانتظار المرسل",
  "transfer.confirmPinBtn": "أكّد بالـ PIN",
  "transfer.declineBtn": "ارفض الحوالة",
  "transfer.pendingPinTitle": "تأكيد الحوالة المعلّقة",
  "transfer.pinTitle": "تأكيد الحوالة",
  "transfer.toReceiverDesc": "إلى {name} — لا تنعكس العملية بعد التنفيذ",
  "transfer.enterPinDesc": "أدخل رمزك السري",
  "transfer.executeBtn": "نفّذ الحوالة",
  "transfer.sentToastTitle": "وصلت الحوالة ✅",
  "transfer.cancelToastTitle": "تم الإلغاء",
  "transfer.cancelFailTitle": "تعذر الإلغاء",
  "transfer.declineToastTitle": "تم الرفض",
  "transfer.declineFailTitle": "تعذر الرفض",
  "transfer.failed": "فشل التحويل",
  "transfer.createFailTitle": "تعذر إنشاء التحويل",
  "transfer.title": "حوّل لأي مستخدم",
  "transfer.subtitle": "دوّر على المستلم بالاسم أو رقم بطاقته — التحويل يتطلب تأكيد الـ PIN.",
  "transfer.againBtn": "حوّل مرة ثانية",
  "transfer.searchLabel": "ابحث بالاسم",
  "transfer.searchPlaceholder": "مثال: أحمد علي — أو زينب…",
  "transfer.searching": "جاري البحث…",
  "transfer.noResults": "ما لقينا أحد بهذا الاسم — جرب الاسم الثلاثي أو رقم البطاقة.",
  "transfer.recipientLabel": "المستلم",
  "transfer.changeBtn": "تغيير",
  "transfer.cardPlaceholder": "أو أدخل رقم البطاقة — 4539 .... .... ....",
  "transfer.amountLabel": "المبلغ",
  "transfer.exceedsBalance": "المبلغ أكبر من رصيدك ({balance})",
  "transfer.continueBtn": "متابعة التحويل",
  "transfer.howTitle": "شلون تشتغلة التحويلات؟",
  "transfer.how1": "تدور على المستلم (من 100 مستخدم مسجل بالمنصة) أو تكتب بطاقته مباشرة.",
  "transfer.how2": "تنشئ طلب تحويل مؤكد — ما ينفذ إلا بعد رمز الـ PIN.",
  "transfer.how3": "تستلم إيصالًا برقم مرجعي، ويوصل المبلغ فوري للطرف الثاني.",
  "transfer.how4": "إذا ما أكّدت الطلب خلال 24 ساعة — ينتهي تلقائيًا ويرجع رصيدك محفوظ.",
  "transfer.favTitle": "المفضلين",
  "transfer.favHint": "اضغط للتحويل السريع",
  "transfer.favEmpty": "ما عندك مفضلين بعد — ⭐ زر المفضلة جانب المستلم يضيفهم هنا",
  "transfer.favRemoveToastTitle": "انحذف من المفضلة",
  "transfer.favAddBtn": "للمفضلة",
  "transfer.favAddedToastTitle": "تمت الإضافة للمفضلة ⭐",
  "transfer.favFailToastTitle": "ما تمت الإضافة",

  /* ---- QR receive / scan ---- */
  "transfer.qrSectionTitle": "استلم حوالة بالـ QR",
  "transfer.qrSectionHint": "اعرض رمزك — الطرف الثاني يمسحه وتتعبى بياناتك عنده",
  "transfer.qrOpenBtn": "رمز الاستلام",
  "transfer.qrScanBtn": "امسح رمز",
  "transfer.qrDialogTitle": "رمز الاستلام",
  "transfer.qrDialogDesc": "خلّي المرسل يمسح الرمز بكاميرته — تتعبى بياناتك تلقائيًا عنده",
  "transfer.qrCardLabel": "رقم بطاقة أور پاي",
  "transfer.qrCopyBtn": "انسخ الرقم",
  "transfer.qrCopied": "انتسخ الرقم",
  "transfer.qrShareBtn": "شارك",
  "transfer.qrDownloadBtn": "حفظ صورة",
  "transfer.qrSavedToast": "انحفظت صورة الرمز",
  "transfer.qrScanTitle": "امسح رمز QR",
  "transfer.qrScanDesc": "وجّه الكاميرا لرمز استلام أور پاي — أو استخدم الإدخال اليدوي",
  "transfer.qrCameraOn": "الكاميرا شغّالة — وجّهها للرمز…",
  "transfer.qrCameraDenied": "الكاميرا غير متاحة من هذا المتصفح — استخدم الإدخال اليدوي",
  "transfer.qrUploadBtn": "فك من صورة",
  "transfer.qrPasteLabel": "رمز QR أو رقم البطاقة",
  "transfer.qrPastePlaceholder": "URPAY:4539... أو 4539 1234 1234 1234",
  "transfer.qrParseBtn": "استخدم الرمز",
  "transfer.qrInvalid": "رمز غير صالح — تأكد منه وجرب مرة ثانية",
  "transfer.qrResolvedToast": "تم التعرف على المستلم",
  "transfer.qrFoundByCard": "مستلم من رمز QR",
  "transfer.qrScannerName": "مسح QR",
  "transfer.qrAmountToggle": "استلم مبلغًا محددًا",
  "transfer.qrAmountHint": "ثبّت المبلغ بالرمز — يتعبى تلقائيًا عند المسح",
  "transfer.qrAmountPlaceholder": "المبلغ",
  "transfer.qrAmountInvalid": "المبلغ لازم يكون بين ١,٠٠٠ و ٥,٠٠٠,٠٠٠ د.ع",

  /* ---- analytics ---- */
  "analytics.title": "تحليلات الإنفاق",
  "analytics.lastPrefix": "آخر",
  "analytics.daysSpent": "يوم — صرفك:",
  "analytics.overdueBadge": "{n} فاتورة متأخرة",
  "analytics.totalSpend": "إجمالي الصرف",
  "analytics.monthlyTitle": "الحركة الشهرية (داخل / خارج)",
  "analytics.barIn": "وارد",
  "analytics.barOut": "صادر",
  "analytics.topCounterparties": "أكثر الناس اللي حوّلتلهم",
  "analytics.transfersCount": "{n} حوالة",
  "analytics.catTransfer": "تحويلات",
  "analytics.catOther": "أخرى",

  /* ---- budget ---- */
  "budget.catTransfer": "تحويلات",
  "budget.statusOver": "تجاوزت الحد",
  "budget.statusNear": "قربت توصل الحد",
  "budget.statusOk": "ضمن الحد",
  "budget.of": " من ",
  "budget.remaining": "باقي {amount} د.ع",
  "budget.overBy": "زائد {amount} د.ع",
  "budget.ariaBudget": "ميزانية {cat}",
  "budget.ariaEdit": "تعديل ميزانية {cat}",
  "budget.title": "ميزانياتي الشهرية",
  "budget.monthPrefix": "شهر {month} — إجمالي:",
  "budget.newBtn": "ميزانية جديدة",
  "budget.chatHint": "جرّب أيضًا من المحادثة: «ميزانية الكهرباء 150 ألف»",
  "budget.emptyTitle": "حدد ميزانية لصرفك الشهري",
  "budget.emptyDesc": "حط حد شهري لأي تصنيف (كهرباء، ماء، تحويلات…) — نراقب صرفك ونخبرك قبل لا يتجاوز الحد. 📊",
  "budget.startBtn": "ابدأ الآن",
  "budget.editTitle": "تعديل ميزانية {cat}",
  "budget.dialogDesc": "حد شهري لتصنيف واحد — نراقب صرفك وننبهك عند التجاوز. تعديل الميزانية ما يحتاج PIN.",
  "budget.categoryLabel": "التصنيف",
  "budget.selectCategory": "اختر التصنيف",
  "budget.limitLabel": "الحد الشهري (د.ع)",
  "budget.q50k": "50k",
  "budget.q100k": "100k",
  "budget.q250k": "250k",
  "budget.q500k": "500k",
  "budget.q1m": "1M",
  "budget.errCategory": "اختر التصنيف أولًا",
  "budget.errMin": "الحد لازم يكون 1,000 د.ع على الأقل",
  "budget.errMax": "الحد الأقصى 20,000,000 د.ع",
  "budget.deleteBtn": "حذف",
  "budget.saveBtn": "حفظ الميزانية",
  "budget.removedToast": "انحذفت الميزانية",
  "budget.savedToast": "تم حفظ الميزانية ✅",
  "budget.saveFailToast": "ما تم الحفظ",
  "budget.tryAgain": "حاول مرة ثانية",

  /* ---- scheduled payments ---- */
  "scheduled.title": "المدفوعات المجدولة",
  "scheduled.subtitle": "تنفّذ تلقائيًا بوقتها — حتى لو نسيتها",
  "scheduled.newBtn": "جدولة دفع",
  "scheduled.emptyTitle": "ما عندك جدولات بعد",
  "scheduled.emptyDesc": "جدّل فاتورة أو حوالة وتننفذ تلقائيًا بوقتها — بدون ما تتذكرها.",
  "scheduled.monthlyBadge": "شهريًا",
  "scheduled.onceBadge": "مرة واحدة",
  "scheduled.nextRun": "تننفذ {when}",
  "scheduled.countdown": "باقي {left}",
  "scheduled.cancelBtn": "إلغاء",
  "scheduled.cancelToastTitle": "تم إلغاء الجدولة",
  "scheduled.monthlyTotal": "الإجمالي الشهري",
  "scheduled.historyTitle": "آخر التنفيذات",
  "scheduled.statusExecuted": "نُفّذت",
  "scheduled.statusCancelled": "أُلغيت",
  "scheduled.statusFailed": "تعذّرت",
  "scheduled.dialogTitle": "جدولة دفع",
  "scheduled.dialogDesc": "تخويل لمرة واحدة برمز الـ PIN — التنفيذ بعدين تلقائي بدون PIN.",
  "scheduled.kindBill": "فاتورة",
  "scheduled.kindTransfer": "حوالة",
  "scheduled.billerLabel": "الجهة",
  "scheduled.receiverLabel": "بطاقة المستلم (16 رقم)",
  "scheduled.amountLabel": "المبلغ",
  "scheduled.whenLabel": "وقت التنفيذ",
  "scheduled.freqLabel": "التكرار",
  "scheduled.freqOnce": "مرة واحدة",
  "scheduled.freqMonthly": "كل شهر",
  "scheduled.whenTomorrow": "غدًا ٩:00 ص",
  "scheduled.when3days": "بعد 3 أيام",
  "scheduled.whenFirstOfMonth": "أول الشهر الجاي",
  "scheduled.whenCustom": "تاريخ مخصص",
  "scheduled.customLabel": "اختر التاريخ والوقت",
  "scheduled.pinTitle": "تأكيد الجدولة",
  "scheduled.pinDesc": "أدخل رمزك لتخويل الجدولة — ستنفّذ تلقائيًا بوقتها",
  "scheduled.pinConfirm": "خوّل الجدولة",
  "scheduled.successToastTitle": "تمت الجدولة بنجاح ✅",
  "scheduled.failToastTitle": "ما تمت الجدولة",
  "scheduled.autopayHint": "أور ينفّذها عنك تلقائيًا — جرّب أيضًا: «جدّل فاتورة الكهرباء أول الشهر»",
  "scheduled.billIconTitle": "فاتورة مجدولة",
  "scheduled.transferIconTitle": "حوالة مجدولة",
  "scheduled.editBtn": "عدّل الجدولة",
  "scheduled.editDialogTitle": "تعديل الجدولة",
  "scheduled.editDialogDesc": "غيّر المبلغ أو موعد التنفيذ — يتطلب رمز الـ PIN.",
  "scheduled.editAmountLabel": "المبلغ الجديد",
  "scheduled.editWhenLabel": "موعد التنفيذ الجديد",
  "scheduled.editKeepWhen": "إبقاء الموعد الحالي",
  "scheduled.editPinTitle": "تأكيد التعديل",
  "scheduled.editPinDesc": "أدخل رمزك لتعديل الجدولة",
  "scheduled.editPinConfirm": "اعتمد التعديل",
  "scheduled.editToastTitle": "تم تعديل الجدولة ✅",
  "scheduled.editFailTitle": "ما تم التعديل",
};

export const en: Record<string, string> = {
  /* ---- shared across dashboard views ---- */
  "common.iqd": "IQD",
  "common.unexpectedError": "Unexpected error",
  "common.opFailed": "Operation failed",
  "common.tryAgain": "Try again",
  "common.cancel": "Cancel",
  "common.loading": "Loading…",

  /* ---- overview ---- */
  "overview.greetingMorning": "Good morning",
  "overview.greetingAfternoon": "Good afternoon",
  "overview.greetingEvening": "Good evening",
  "overview.greetingLine": "{greeting}, {name} {emoji} — your available balance",
  "overview.walletBadge": "UrPay wallet",
  "overview.demoBadge": "Demo account",
  "overview.payBillBtn": "Pay a Bill",
  "overview.transferBtn": "Send",
  "overview.topUpBtn": "Top Up",
  "overview.askUrBtn": "Ask Ur",
  "overview.overdueAlertStart": "You have",
  "overview.overdueAlertEnd": "overdue — let Ur clear them before they pile up.",
  "overview.showBillsBtn": "View Bills",
  "overview.upcomingBillsTitle": "Upcoming Bills",
  "overview.billsCountSuffix": "bills totalling",
  "overview.viewAllBtn": "View All",
  "overview.recentTitle": "Recent Activity",
  "overview.fullHistoryBtn": "Full History",
  "overview.noUnpaidDesc": "Nice! Try generating a demo bill from the Bills page, or just ask Ur.",
  "overview.noTxns": "No transactions yet — start by paying a bill!",
  "overview.tryUrTitle": "Try Ur Now",
  "overview.tryUrDesc": "Type “pay the electricity bill” or “what's my balance?” — it all happens in one chat.",
  "overview.chipBalance": "What's my balance?",
  "overview.chipBills": "My bills",
  "overview.chipPayBill": "Pay the electricity bill",
  "overview.openChatBtn": "Open Chat",
  "overview.doneCloseBtn": "Done",
  "overview.topupToastTitle": "Top-up complete ✅",
  "overview.topupToastDesc": "Added {amount} — your balance is now {balance}",
  "overview.topupDialogTitle": "Top Up Your Wallet",
  "overview.topupDialogDesc": "Simulated cash deposit at an UrPay agent — requires PIN confirmation.",
  "overview.topupContinueBtn": "Continue",
  "overview.topupPinTitle": "Confirm Wallet Top-Up",
  "overview.topupPinDesc": "Cash deposit — UrPay agent (simulated)",
  "overview.topupPinConfirm": "Complete Top-Up",

  /* ---- bills ---- */
  "bills.title": "Bills",
  "bills.unpaidTotal": "Unpaid total: {total}",
  "bills.allPaid": "All your bills are paid 🎉",
  "bills.count": "{n} bills",
  "bills.simulateBtn": "Generate a Demo Bill",
  "bills.tabUnpaid": "Unpaid",
  "bills.tabPaid": "Paid",
  "bills.tabAll": "All",
  "bills.noUnpaidTitle": "No unpaid bills",
  "bills.noneInFilterTitle": "No bills in this category",
  "bills.emptyDesc": "Generate a demo bill and try the full payment flow with your PIN and a reference receipt.",
  "bills.simulateShortBtn": "Generate a Bill",
  "bills.payConfirmTitle": "Confirm Bill Payment",
  "bills.noPeriod": "no period",
  "bills.payNowBtn": "Pay Now",
  "bills.paidToastTitle": "Payment successful ✅",
  "bills.receiptTitle": "Payment Receipt",
  "bills.receiptDesc": "Details of the successful transaction",
  "bills.simulateDesc": "A new bill is added to your list — perfect for trying the Ur assistant or paying directly.",
  "bills.categoryLabel": "Category",
  "bills.billerLabel": "Biller",
  "bills.selectBiller": "Select a biller",
  "bills.subscriberLabel": "Subscriber number",
  "bills.amountLabel": "Amount (IQD)",
  "bills.generateBtn": "Generate Bill",
  "bills.generatedToastTitle": "Bill generated ✨",
  "bills.generatedToastDesc": "It's ready in your list — pay it yourself or let Ur handle it",
  "bills.generateFailTitle": "Couldn't generate the bill",

  /* ---- transfer ---- */
  "transfer.ttlExpiring": "Expiring soon",
  "transfer.ttlHm": "{h}h {m}m",
  "transfer.ttlMins": "{m} min",
  "transfer.ttlExpiresIn": "Expires in {label}",
  "transfer.pendingTitle": "Pending Requests",
  "transfer.pendingHint": "They auto-expire 24 hours after creation",
  "transfer.badgeOutgoing": "Outgoing — awaiting your confirmation",
  "transfer.badgeIncoming": "Incoming — awaiting the sender",
  "transfer.confirmPinBtn": "Confirm with PIN",
  "transfer.declineBtn": "Decline Transfer",
  "transfer.pendingPinTitle": "Confirm Pending Transfer",
  "transfer.pinTitle": "Confirm Transfer",
  "transfer.toReceiverDesc": "To {name} — it can't be reversed once executed",
  "transfer.enterPinDesc": "Enter your PIN",
  "transfer.executeBtn": "Complete Transfer",
  "transfer.sentToastTitle": "Transfer complete ✅",
  "transfer.cancelToastTitle": "Cancelled",
  "transfer.cancelFailTitle": "Cancel failed",
  "transfer.declineToastTitle": "Declined",
  "transfer.declineFailTitle": "Decline failed",
  "transfer.failed": "Transfer failed",
  "transfer.createFailTitle": "Couldn't create the transfer",
  "transfer.title": "Send money to anyone",
  "transfer.subtitle": "Find the recipient by name or card number — transfers require PIN confirmation.",
  "transfer.againBtn": "Send Again",
  "transfer.searchLabel": "Search by name",
  "transfer.searchPlaceholder": "e.g. Ahmed Ali — or Zainab…",
  "transfer.searching": "Searching…",
  "transfer.noResults": "No one found with that name — try the full three-part name or a card number.",
  "transfer.recipientLabel": "Recipient",
  "transfer.changeBtn": "Change",
  "transfer.cardPlaceholder": "or enter a card number — 4539 .... .... ....",
  "transfer.amountLabel": "Amount",
  "transfer.exceedsBalance": "Amount exceeds your balance ({balance})",
  "transfer.continueBtn": "Continue",
  "transfer.howTitle": "How do transfers work?",
  "transfer.how1": "Find the recipient (from 100 registered users) or type their card number directly.",
  "transfer.how2": "A transfer request is created — it only goes through after your PIN.",
  "transfer.how3": "You receive a receipt with a reference number, and the money arrives instantly.",
  "transfer.how4": "If you don't confirm within 24 hours, it expires automatically and your balance stays intact.",
  "transfer.favTitle": "Favorites",
  "transfer.favHint": "Tap for a quick transfer",
  "transfer.favEmpty": "No favorites yet — tap the ⭐ next to a recipient to add them here",
  "transfer.favRemoveToastTitle": "Removed from favorites",

  /* ---- QR receive / scan ---- */
  "transfer.qrSectionTitle": "Receive via QR",
  "transfer.qrSectionHint": "Show your code — the sender scans it and your details fill in",
  "transfer.qrOpenBtn": "My QR",
  "transfer.qrScanBtn": "Scan",
  "transfer.qrDialogTitle": "Your receive code",
  "transfer.qrDialogDesc": "Let the sender scan it with their camera — your details fill in automatically",
  "transfer.qrCardLabel": "UrPay card number",
  "transfer.qrCopyBtn": "Copy number",
  "transfer.qrCopied": "Copied",
  "transfer.qrShareBtn": "Share",
  "transfer.qrDownloadBtn": "Save image",
  "transfer.qrSavedToast": "QR image saved",
  "transfer.qrAmountToggle": "Request a specific amount",
  "transfer.qrAmountHint": "Pin the amount into the code — it fills in automatically on scan",
  "transfer.qrAmountPlaceholder": "Amount",
  "transfer.qrAmountInvalid": "Amount must be between 1,000 and 5,000,000 IQD",
  "transfer.qrScanTitle": "Scan a QR code",
  "transfer.qrScanDesc": "Point the camera at an UrPay receive code — or use manual entry below",
  "transfer.qrCameraOn": "Camera live — point it at the code…",
  "transfer.qrCameraDenied": "Camera not available in this browser — use manual entry",
  "transfer.qrUploadBtn": "Decode from image",
  "transfer.qrPasteLabel": "QR payload or card number",
  "transfer.qrPastePlaceholder": "URPAY:4539... or 4539 1234 1234 1234",
  "transfer.qrParseBtn": "Use code",
  "transfer.qrInvalid": "Invalid code — check it and try again",
  "transfer.qrResolvedToast": "Recipient recognised",
  "transfer.qrFoundByCard": "Recipient from QR",
  "transfer.qrScannerName": "QR scan",
  "transfer.favAddBtn": "Favorite",
  "transfer.favAddedToastTitle": "Added to favorites ⭐",
  "transfer.favFailToastTitle": "Couldn't add",

  /* ---- analytics ---- */
  "analytics.title": "Spending Analytics",
  "analytics.lastPrefix": "Last",
  "analytics.daysSpent": "days — you spent:",
  "analytics.overdueBadge": "{n} overdue",
  "analytics.totalSpend": "Total spend",
  "analytics.monthlyTitle": "Monthly Flow (In / Out)",
  "analytics.barIn": "In",
  "analytics.barOut": "Out",
  "analytics.topCounterparties": "Top Recipients",
  "analytics.transfersCount": "{n} transfers",
  "analytics.catTransfer": "Transfers",
  "analytics.catOther": "Other",

  /* ---- budget ---- */
  "budget.catTransfer": "Transfers",
  "budget.statusOver": "Over limit",
  "budget.statusNear": "Near limit",
  "budget.statusOk": "Within limit",
  "budget.of": " of ",
  "budget.remaining": "{amount} IQD left",
  "budget.overBy": "{amount} IQD over",
  "budget.ariaBudget": "{cat} budget",
  "budget.ariaEdit": "Edit {cat} budget",
  "budget.title": "My Monthly Budgets",
  "budget.monthPrefix": "{month} — total:",
  "budget.newBtn": "New Budget",
  "budget.chatHint": "You can also do it in chat: “Electricity budget 150k”",
  "budget.emptyTitle": "Set a Monthly Spending Budget",
  "budget.emptyDesc": "Set a monthly limit for any category (electricity, water, transfers…) — we track your spend and alert you before you cross it. 📊",
  "budget.startBtn": "Get Started",
  "budget.editTitle": "Edit {cat} Budget",
  "budget.dialogDesc": "A monthly limit for one category — we watch your spend and notify you when you cross it. Editing a budget doesn't require a PIN.",
  "budget.categoryLabel": "Category",
  "budget.selectCategory": "Select a category",
  "budget.limitLabel": "Monthly Limit (IQD)",
  "budget.q50k": "50k",
  "budget.q100k": "100k",
  "budget.q250k": "250k",
  "budget.q500k": "500k",
  "budget.q1m": "1M",
  "budget.errCategory": "Choose a category first",
  "budget.errMin": "The limit must be at least 1,000 IQD",
  "budget.errMax": "The maximum limit is 20,000,000 IQD",
  "budget.deleteBtn": "Delete",
  "budget.saveBtn": "Save Budget",
  "budget.removedToast": "Budget deleted",
  "budget.savedToast": "Budget saved ✅",
  "budget.saveFailToast": "Couldn't save the budget",
  "budget.tryAgain": "Try again",

  /* ---- scheduled payments ---- */
  "scheduled.title": "Scheduled Payments",
  "scheduled.subtitle": "Executed automatically on time — even if you forget",
  "scheduled.newBtn": "Schedule a payment",
  "scheduled.emptyTitle": "No scheduled payments yet",
  "scheduled.emptyDesc": "Schedule a bill or transfer and it executes itself at the right time — no reminders needed.",
  "scheduled.monthlyBadge": "Monthly",
  "scheduled.onceBadge": "Once",
  "scheduled.nextRun": "Runs {when}",
  "scheduled.countdown": "in {left}",
  "scheduled.cancelBtn": "Cancel",
  "scheduled.cancelToastTitle": "Schedule cancelled",
  "scheduled.monthlyTotal": "Monthly total",
  "scheduled.historyTitle": "Recent runs",
  "scheduled.statusExecuted": "Executed",
  "scheduled.statusCancelled": "Cancelled",
  "scheduled.statusFailed": "Failed",
  "scheduled.dialogTitle": "Schedule a payment",
  "scheduled.dialogDesc": "One-time PIN authorization — it then executes automatically, no PIN needed later.",
  "scheduled.kindBill": "Bill",
  "scheduled.kindTransfer": "Transfer",
  "scheduled.billerLabel": "Biller",
  "scheduled.receiverLabel": "Recipient card (16 digits)",
  "scheduled.amountLabel": "Amount",
  "scheduled.whenLabel": "When",
  "scheduled.freqLabel": "Repeat",
  "scheduled.freqOnce": "Once",
  "scheduled.freqMonthly": "Every month",
  "scheduled.whenTomorrow": "Tomorrow 9:00 AM",
  "scheduled.when3days": "In 3 days",
  "scheduled.whenFirstOfMonth": "First of next month",
  "scheduled.whenCustom": "Custom date",
  "scheduled.customLabel": "Pick date & time",
  "scheduled.pinTitle": "Confirm schedule",
  "scheduled.pinDesc": "Enter your PIN to authorize — it will run automatically on time",
  "scheduled.pinConfirm": "Authorize schedule",
  "scheduled.successToastTitle": "Scheduled successfully ✅",
  "scheduled.failToastTitle": "Couldn't schedule",
  "scheduled.autopayHint": "Ur executes it for you — try: «جدّل فاتورة الكهرباء أول الشهر»",
  "scheduled.billIconTitle": "Scheduled bill",
  "scheduled.transferIconTitle": "Scheduled transfer",
  "scheduled.editBtn": "Edit schedule",
  "scheduled.editDialogTitle": "Edit schedule",
  "scheduled.editDialogDesc": "Change the amount or the run time — requires your PIN.",
  "scheduled.editAmountLabel": "New amount",
  "scheduled.editWhenLabel": "New run time",
  "scheduled.editKeepWhen": "Keep current time",
  "scheduled.editPinTitle": "Confirm edit",
  "scheduled.editPinDesc": "Enter your PIN to apply the change",
  "scheduled.editPinConfirm": "Apply change",
  "scheduled.editToastTitle": "Schedule updated ✅",
  "scheduled.editFailTitle": "Edit failed",
};
