/**
 * Dictionary — misc namespaces: shell/nav, agent, transactions, profile,
 * notifications, shared parts (PinDialog/ReceiptCard/EmptyState), theme, common.
 * OWNED BY: misc conversion task. Add keys here, do not create other dict files.
 */
export const ar: Record<string, string> = {
  /* dashboard shell — nav / header / sidebar promo */
  "shell.nav.overview": "نظرة عامة",
  "shell.nav.bills": "الفواتير",
  "shell.nav.transfer": "تحويل",
  "shell.nav.agent": "المساعد أور",
  "shell.nav.transactions": "السجل",
  "shell.nav.profile": "حسابي",
  "shell.balance": "الرصيد",
  "shell.refresh": "تحديث",
  "shell.logout": "تسجيل الخروج",
  "shell.logoutDone": "تم تسجيل الخروج",
  "shell.logoutBye": "نشتاقلك! ترجع بأي وقت.",
  "shell.sidebarNav": "قائمة اللوحة",
  "shell.bottomNav": "التنقل السفلي",
  "shell.promo.title": "خلّي أور يدفع فواتيرك",
  "shell.promo.desc": "محادثة وحدة تكفي — يفهم، يتحقق، يطلب PIN، وينفّذ.",
  "shell.promo.cta": "افتح المحادثة",

  /* agent chat */
  "agent.title": "أور · وكيل الدفع الذكي",
  "agent.providerLocal": "المحرك المحلي",
  "agent.online": "متصل — Groq gpt-oss-120b",
  "agent.yourBalance": "رصيدك: {n} د.ع",
  "agent.copyAria": "نسخ المحادثة",
  "agent.copy": "نسخ",
  "agent.copied": "انتسخت",
  "agent.downloadAria": "تنزيل المحادثة ملف نصي",
  "agent.download": "ملف",
  "agent.newChat": "محادثة جديدة",
  "agent.welcomeTitle": "هلا {name}! أنا أور — وكيلك المالي",
  "agent.welcomeDefault": "بك",
  "agent.welcomeDesc": "أقدر أدفع فواتيرك، أسويلك تحويلات، أچيك رصيدك وأسرد معاملاتك — كل شي من هنا. أي دفعة بيطلب مني الـ PIN مالك.",
  "agent.thinking": "أور يفكر…",
  "agent.placeholder": "اكتب لأور… (مثال: ادفع فاتورة الإنترنت)",
  "agent.inputAria": "رسالة للمساعد أور",
  "agent.send": "إرسال",
  "agent.disclaimer": "الوكيل ينفّذ أدوات حقيقية (رصيد، فواتير، دفع، تحويل) — أي عملية دفع تتطلب PIN.",
  "agent.error.connection": "صار خطأ بالاتصال: {msg}",
  "agent.error.retry": "حاول مرة ثانية",
  "agent.transcript.assistant": "🤖 أور: {content}",
  "agent.transcript.footer": "— محادثة أور پاي · {date}",

  /* transactions history */
  "txns.filter.all": "الكل",
  "txns.filter.billPayment": "فواتير",
  "txns.filter.transferOut": "تحويلات صادرة",
  "txns.filter.transferIn": "تحويلات واردة",
  "txns.filter.topup": "شحن وإيداع",
  "txns.exportOk": "تم تصدير السجل ✅",
  "txns.exportOkDesc": "انتحَل ملف CSV بكل معاملاتك — يفتح مباشرة بإكسل.",
  "txns.exportFail": "تعذّر التصدير",
  "txns.exportFailDesc": "جرّب مرة ثانية بعد شوية.",
  "txns.exportCsv": "تصدير CSV",
  "txns.exporting": "يجمع…",
  "txns.exported": "انتحَل الملف",
  "txns.title": "سجل المعاملات",
  "txns.subtitle": "كل حركة بمحفظتك — مع الرقم المرجعي والرصيد بعد كل عملية.",
  "txns.outTotal": "صادر",
  "txns.inTotal": "وارد",
  "txns.currentBalance": "الرصيد الحالي",
  "txns.emptyTitle": "ما هني معاملات بهذا التصنيف",
  "txns.emptyDesc": "جرّب تصنيفًا آخر، أو ابدأ بدفع فاتورة أو تحويل.",
  "txns.lastN": "أُظهرت آخر {n} معاملة",

  /* profile */
  "profile.changePin": "غيّر رمز الـ PIN",
  "profile.changePinDesc": "أدخل رمزك الحالي للتأكيد — الرمز الجديد يُفعّل فورًا لكل العمليات.",
  "profile.pinChanged": "تم التغيير ✅",
  "profile.pinUpdateFail": "تعذر تحديث الرمز",
  "profile.currentPin": "الرمز الحالي",
  "profile.newPin": "الرمز الجديد",
  "profile.confirmPin": "تأكيد الرمز",
  "profile.pinMismatch": "التأكيد ما يطابق الرمز الجديد",
  "profile.updatePin": "حدّث الرمز",
  "profile.field.name": "الاسم الثلاثي",
  "profile.field.age": "العمر",
  "profile.field.city": "المحافظة (السكن)",
  "profile.field.phone": "الهاتف",
  "profile.field.card": "رقم البطاقة",
  "profile.field.memberSince": "عضو منذ",
  "profile.yearsOld": "{n} سنة",
  "profile.cardShort": "بطاقة",
  "profile.demoAccount": "حساب تجريبي",
  "profile.changePinCardDesc": "رمز جديد لكل عمليات الدفع والتحويل — يتطلب الرمز الحالي.",
  "profile.appearance": "مظهر المحفظة",
  "profile.appearanceSuffix": " — بدّل حسب راحتك.",
  "profile.themeLight": "نهاري",
  "profile.themeDark": "ليلي",
  "profile.detailsTitle": "بيانات التسجيل",
  "profile.securityTitle": "أمان حسابك",
  "profile.securityPin": "الـ PIN مخزّن PBKDF2-SHA256 مع ملح فردي — الدفع يتطلبه دائمًا.",
  "profile.securityJwt": "جلساتك موقّعة JWT وتنتهي تلقائيًا بعد ٧ أيام.",
  "profile.techTitle": "تقنية المنصة",
  "profile.hackathonNote": "نسخة هاكاثون — البيانات تجريبية بالكامل ولا تمثل أموالًا حقيقية.",
  "profile.tryAgent": "جرّب المساعد أور",

  /* notifications bell */
  "notif.bellAria": "الإشعارات",
  "notif.unreadAria": "الإشعارات — {n} غير مقروء",
  "notif.title": "الإشعارات",
  "notif.newCount": "{n} جديد",
  "notif.markAll": "علّم الكل",
  "notif.emptyTitle": "ما وصلك إشعار بعد",
  "notif.emptyDesc": "هيج رح تطلع هنا فواتيرك المستحقة، التحويلات، وكل عملية دفع.",
  "notif.footerHint": "اضغط على الإشعار لتعليمه كمقروء · تحدّث تلقائيًا",

  /* shared parts — PinDialog / ReceiptCard / BillRow / TxnRow */
  "parts.confirm": "تأكيد العملية",
  "parts.unexpectedError": "صار خطأ غير متوقع — حاول مرة ثانية",
  "parts.pinHint": "أدخل رمزك السري (4–6 أرقام) — نفس PIN التسجيل",
  "parts.receiptSuccess": "عملية ناجحة",
  "parts.receipt": "إيصال",
  "parts.reference": "الرقم المرجعي",
  "parts.copyReference": "انسخ الرقم المرجعي",
  "parts.balanceAfter": "الرصيد بعد العملية",
  "parts.overdue": "متأخرة",
  "parts.paid": "مدفوعة",
  "parts.noPeriod": "بلا فترة",
  "parts.subscription": "اشتراك",
  "parts.due": "الاستحقاق:",
  "parts.iqd": "د.ع",
  "parts.payNow": "ادفع الآن",
  "parts.balance": "رصيد: {n}",

  /* theme toggle */
  "theme.dark": "الوضع الليلي",
  "theme.light": "الوضع النهاري",
  "theme.toDark": "بدّل للوضع الليلي",
  "theme.toLight": "بدّل للوضع النهاري",
  "theme.darkOn": "الوضع الليلي مفعّل",
  "theme.lightOn": "الوضع النهاري مفعّل",

  /* language toggle */
  "lang.arabic": "العربية",
  "lang.english": "English",
  "lang.toArabic": "بدّل إلى العربية",
  "lang.toEnglish": "Switch to English",
  "lang.arabicOn": "الواجهة بالعربية",
  "lang.englishOn": "Interface in English",
};

export const en: Record<string, string> = {
  /* dashboard shell — nav / header / sidebar promo */
  "shell.nav.overview": "Overview",
  "shell.nav.bills": "Bills",
  "shell.nav.transfer": "Transfer",
  "shell.nav.agent": "Agent Ur",
  "shell.nav.transactions": "History",
  "shell.nav.profile": "My Account",
  "shell.balance": "Balance",
  "shell.refresh": "Refresh",
  "shell.logout": "Log Out",
  "shell.logoutDone": "Signed out",
  "shell.logoutBye": "We'll miss you! Come back anytime.",
  "shell.sidebarNav": "Dashboard menu",
  "shell.bottomNav": "Bottom navigation",
  "shell.promo.title": "Let Ur pay your bills",
  "shell.promo.desc": "One conversation is all it takes — he understands, verifies, asks for your PIN, and executes.",
  "shell.promo.cta": "Open Chat",

  /* agent chat */
  "agent.title": "Ur · your payment agent",
  "agent.providerLocal": "Local engine",
  "agent.online": "Online — Groq gpt-oss-120b",
  "agent.yourBalance": "Your balance: {n} IQD",
  "agent.copyAria": "Copy conversation",
  "agent.copy": "Copy",
  "agent.copied": "Copied",
  "agent.downloadAria": "Download conversation as a text file",
  "agent.download": "File",
  "agent.newChat": "New Chat",
  "agent.welcomeTitle": "Hi {name}! I'm Ur — your money agent",
  "agent.welcomeDefault": "there",
  "agent.welcomeDesc": "I can pay your bills, make transfers, check your balance and list your transactions — all from here. Any payment will ask for your PIN.",
  "agent.thinking": "Ur is thinking…",
  "agent.placeholder": "Write to Ur… (e.g. pay the internet bill)",
  "agent.inputAria": "Message agent Ur",
  "agent.send": "Send",
  "agent.disclaimer": "The agent runs real tools (balance, bills, payments, transfers) — every payment requires your PIN.",
  "agent.error.connection": "Connection error: {msg}",
  "agent.error.retry": "please try again",
  "agent.transcript.assistant": "🤖 Ur: {content}",
  "agent.transcript.footer": "— UrPay chat · {date}",

  /* transactions history */
  "txns.filter.all": "All",
  "txns.filter.billPayment": "Bills",
  "txns.filter.transferOut": "Outgoing Transfers",
  "txns.filter.transferIn": "Incoming Transfers",
  "txns.filter.topup": "Top-ups & Deposits",
  "txns.exportOk": "History exported ✅",
  "txns.exportOkDesc": "Your CSV with all transactions has been downloaded — opens directly in Excel.",
  "txns.exportFail": "Export failed",
  "txns.exportFailDesc": "Please try again in a moment.",
  "txns.exportCsv": "Export CSV",
  "txns.exporting": "Collecting…",
  "txns.exported": "File downloaded",
  "txns.title": "Transaction History",
  "txns.subtitle": "Every movement in your wallet — with the reference number and balance after each one.",
  "txns.outTotal": "Outgoing",
  "txns.inTotal": "Incoming",
  "txns.currentBalance": "Current balance",
  "txns.emptyTitle": "No transactions in this category",
  "txns.emptyDesc": "Try another filter, or start by paying a bill or making a transfer.",
  "txns.lastN": "Showing the last {n} transactions",

  /* profile */
  "profile.changePin": "Change Your PIN",
  "profile.changePinDesc": "Enter your current PIN to confirm — the new one takes effect immediately for all operations.",
  "profile.pinChanged": "Changed ✅",
  "profile.pinUpdateFail": "Could not update the PIN",
  "profile.currentPin": "Current PIN",
  "profile.newPin": "New PIN",
  "profile.confirmPin": "Confirm PIN",
  "profile.pinMismatch": "Confirmation doesn't match the new PIN",
  "profile.updatePin": "Update PIN",
  "profile.field.name": "Full name",
  "profile.field.age": "Age",
  "profile.field.city": "Governorate (residence)",
  "profile.field.phone": "Phone",
  "profile.field.card": "Card number",
  "profile.field.memberSince": "Member since",
  "profile.yearsOld": "{n} years",
  "profile.cardShort": "card",
  "profile.demoAccount": "Demo account",
  "profile.changePinCardDesc": "A new PIN for all payments and transfers — requires your current one.",
  "profile.appearance": "Wallet appearance",
  "profile.appearanceSuffix": " — switch whenever you like.",
  "profile.themeLight": "Light",
  "profile.themeDark": "Dark",
  "profile.detailsTitle": "Registration details",
  "profile.securityTitle": "Your account security",
  "profile.securityPin": "Your PIN is stored as PBKDF2-SHA256 with an individual salt — payments always require it.",
  "profile.securityJwt": "Your sessions are JWT-signed and expire automatically after 7 days.",
  "profile.techTitle": "Platform tech",
  "profile.hackathonNote": "Hackathon build — all data is demo only and does not represent real money.",
  "profile.tryAgent": "Try Agent Ur",

  /* notifications bell */
  "notif.bellAria": "Notifications",
  "notif.unreadAria": "Notifications — {n} unread",
  "notif.title": "Notifications",
  "notif.newCount": "{n} new",
  "notif.markAll": "Mark All Read",
  "notif.emptyTitle": "No notifications yet",
  "notif.emptyDesc": "Your due bills, transfers and every payment will appear here.",
  "notif.footerHint": "Tap a notification to mark it read · auto-refreshes",

  /* shared parts — PinDialog / ReceiptCard / BillRow / TxnRow */
  "parts.confirm": "Confirm",
  "parts.unexpectedError": "An unexpected error occurred — please try again",
  "parts.pinHint": "Enter your PIN (4–6 digits) — the same one you signed up with",
  "parts.receiptSuccess": "Operation successful",
  "parts.receipt": "Receipt",
  "parts.reference": "Reference number",
  "parts.copyReference": "Copy the reference number",
  "parts.balanceAfter": "Balance after operation",
  "parts.overdue": "Overdue",
  "parts.paid": "Paid",
  "parts.noPeriod": "no period",
  "parts.subscription": "subscriber",
  "parts.due": "Due:",
  "parts.iqd": "IQD",
  "parts.payNow": "Pay Now",
  "parts.balance": "Balance: {n}",

  /* theme toggle */
  "theme.dark": "Dark mode",
  "theme.light": "Light mode",
  "theme.toDark": "Switch to dark mode",
  "theme.toLight": "Switch to light mode",
  "theme.darkOn": "Dark mode active",
  "theme.lightOn": "Light mode active",

  /* language toggle */
  "lang.arabic": "العربية",
  "lang.english": "English",
  "lang.toArabic": "Switch to Arabic",
  "lang.toEnglish": "Switch to English",
  "lang.arabicOn": "Interface in Arabic",
  "lang.englishOn": "Interface in English",
};
