#!/usr/bin/env node
/**
 * Fetch-fonts — one-time utility that self-hosts the Google Fonts used by UrPay.
 *
 * Why: `next/font/google` downloads fonts from fonts.gstatic.com at dev/build
 * time. That is slow and fragile (blocked/flaky networks kill the whole dev
 * server with "Module not found: Can't resolve
 * '@vercel/turbopack-next/internal/font/google/font'"). This script downloads
 * the woff2 files ONCE into public/fonts/ and generates src/app/fonts.css with
 * plain local @font-face rules — zero network dependency afterwards, on any
 * machine (sandbox, Windows, offline demos).
 *
 * Usage: node scripts/fetch-fonts.mjs   (re-run only when fonts change)
 */
import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const FONTS_DIR = path.join(ROOT, "public", "fonts");
const CSS_OUT = path.join(ROOT, "src", "app", "fonts.css");

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const FAMILIES = [
  {
    css2: "family=Inter+Tight:wght@400;500;600;700",
    family: "Inter Tight",
    prefix: "inter-tight",
    subsets: ["latin", "latin-ext"],
  },
  {
    css2: "family=IBM+Plex+Sans+Arabic:wght@300;400;500;600;700",
    family: "IBM Plex Sans Arabic",
    prefix: "plex-arabic",
    subsets: ["arabic", "latin", "latin-ext"],
  },
];

const BLOCK_RE = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;

async function main() {
  await mkdir(FONTS_DIR, { recursive: true });
  const faces = [];

  for (const fam of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?${fam.css2}&display=swap`;
    const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => {
      if (!r.ok) throw new Error(`CSS fetch failed ${r.status} for ${fam.family}`);
      return r.text();
    });

    for (const [, subset, body] of css.matchAll(BLOCK_RE)) {
      if (!fam.subsets.includes(subset)) continue;
      const weight = body.match(/font-weight:\s*(\d+)/)?.[1];
      const src = body.match(/src:\s*url\((https:[^)]+\.woff2)\)/)?.[1];
      const range = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
      if (!weight || !src || !range) continue;

      const file = `${fam.prefix}-${weight}-${subset}.woff2`;
      const dest = path.join(FONTS_DIR, file);
      if (!existsSync(dest)) {
        const buf = Buffer.from(await (await fetch(src)).arrayBuffer());
        if (buf.length < 1000) throw new Error(`Suspicious tiny font: ${src}`);
        await writeFile(dest, buf);
        console.log(`downloaded ${file} (${(buf.length / 1024).toFixed(1)} kB)`);
      } else {
        console.log(`cached    ${file}`);
      }

      faces.push({ family: fam.family, weight, range, file });
    }
  }

  const cssOut = [
    "/* Self-hosted Google Fonts — generated by scripts/fetch-fonts.mjs.",
     "   No network access needed at dev/build time (works offline, any OS). */",
    ...faces.map(
      (f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url('/fonts/${f.file}') format('woff2');
  unicode-range: ${f.range};
}`,
    ),
    "",
  ].join("\n");

  await writeFile(CSS_OUT, cssOut);
  console.log(`\nwrote ${path.relative(ROOT, CSS_OUT)} (${faces.length} @font-face rules)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
